name: macOS CI

on:
  # WARNING: don't allow this on PRs, we only want to run on trusted code out of master
  push:
    branches: [ master ]
  schedule:
    - cron:  '*/30 * * * *'
  workflow_dispatch:


jobs:
  tests:
    name: test on macOS
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/checkout@v2
      - name: brew upgrade earthly
        run: "brew upgrade earthly"
      - name: get earth version
        run: "echo ::set-env name=EARTH_VERSION::`earth --version`"
      - name: "build earth"
        run: "earth +for-darwin"
      - name: "test built earth"
        run: "./build/darwin/amd64/earth -P github.com/earthly/earthly+test-all"
      - name: Report on slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,commit,workflow

          custom_payload: |
          {
            username: 'action-slack',
            icon_emoji: ':octocat:',
            attachments: [{
              color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
              text: `tested with ${env.EARTH_VERSION}\n`,
            }]
          }

          "${env.EARTH_VERSION}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_ALERTS_WEBHOOK_URL }}
        if: always()
