name: macOS CI

on:
  push:
    branches: [ master ]
  schedule:
    - cron:  '*/30 * * * *'
  workflow_dispatch:


jobs:
  tests:
    name: test mac hostname
    if: github.event_name == 'push'
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/checkout@v2
      - name: display hostname
        run: "brew upgrade earthly"
      - name: "build earth"
        run: "earth +for-darwin"
      - name: "test built earth"
        run: "./build/darwin/amd64/earth -P github.com/earthly/earthly+test-all"
