name: macOS CI

on:
  # WARNING: don't allow this on PRs, we only want to run on trusted code out of master
  push:
    branches: [ master ]
  schedule:
    - cron:  '*/30 * * * *'
  workflow_dispatch:


jobs:
  tests:
    name: test on macOS
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/checkout@v2
      - name: display hostname
        run: "brew upgrade earthly"
      - name: "build earth"
        run: "earth +for-darwin"
      - name: "test built earth"
        run: "./build/darwin/amd64/earth -P github.com/earthly/earthly+test-all"
      - name: Report on slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_ALERTS_WEBHOOK_URL }}
        if: failure()
