name: GitHub Actions CI (Windows WSL)

on:
  push:
    branches: [ master ]

defaults:
  run:
    shell: wsl -- bash --noprofile --norc -euo pipefail "$(script="$(wslpath '{0}')" && sed -i 's/\r$//' "$script" && echo "$script")"

jobs:
  tests:
    name: Test (Windows)
    runs-on: [self-hosted, Windows]
    env:
      GIT_URL_INSTEAD_OF: "https://github.com/=git@github.com:"
      FORCE_COLOR: 1
      WSLENV: "GIT_URL_INSTEAD_OF/u:FORCE_COLOR/u"
    steps:
      - uses: actions/checkout@v2
      - name: Download released earth
        run: "/bin/sh -c 'wget https://github.com/earthly/earthly/releases/latest/download/earth-linux-amd64 -O ./earth-released && chmod +x ./earth-released'"
      - name: Build latest earth using released earth
        run: ./earth-released +for-linux
      - name: Execute tests
        run: ./build/linux/amd64/earth --no-output -P +test
      - name: Execute fail test
        run: "! ./build/linux/amd64/earth --no-output +test-fail"
      - name: Execute experimental tests
        run: ./build/linux/amd64/earth --no-output -P ./examples/tests+experimental
      - name: Build examples
        run: ./build/linux/amd64/earth --no-output +examples
      - name: Docker Login
        run: docker login --username vladaionescu --password "${{ secrets.DOCKERHUB_TOKEN }}"
      - name: Execute private image test
        run: ./build/linux/amd64/earth --no-output ./examples/tests+private-image-test
